// Left  - Right reverse
// int layer0[44] = {
//  KEY_QUOTE, KEY_COMMA, KEY_PERIOD, KEY_P, KEY_Y, KEY_0, KEY_F, KEY_G, KEY_C, KEY_R, KEY_L,
//  KEY_A, KEY_O, KEY_E, KEY_U, KEY_I, KEY_0, KEY_D, KEY_H, KEY_T, KEY_N, KEY_S,
//  KEY_SEMICOLON, KEY_Q, KEY_J, KEY_K, KEY_X, KEYBOARD_LEFT_ALT, KEY_B, KEY_M, KEY_W, KEY_V, KEY_Z,
//  KEY_ESC, KEY_TAB, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), KEY_SLASH, KEY_MINUS, KEY_ENTER };

 int layer0[44] = {
   KEY_L, KEY_R, KEY_C, KEY_G, KEY_F, KEY_0, KEY_Y,KEY_P, KEY_PERIOD, KEY_COMMA, KEY_QUOTE,
  KEY_S, KEY_N, KEY_T, KEY_H, KEY_D, KEY_0, KEY_I, KEY_U, KEY_E, KEY_O, KEY_A,
  KEY_Z, KEY_V, KEY_W, KEY_M, KEY_B, KEYBOARD_LEFT_ALT, KEY_X, KEY_K, KEY_J, KEY_Q, KEY_SEMICOLON,
   KEY_TILDE, KEY_SLASH, KEY_MINUS, PRE_FUNCTION(1), KEY_SPACE, KEYBOARD_LEFT_SHIFT, KEYBOARD_LEFT_CTRL, KEY_BACKSPACE, KEYBOARD_LEFT_GUI, KEY_TAB, KEY_ESC };

// int layer1[44] = {
//  SHIFT(KEY_1), SHIFT(KEY_2), SHIFT(KEY_3), SHIFT(KEY_4), SHIFT(KEY_5), KEY_0, SHIFT(KEY_6), SHIFT(KEY_7), SHIFT(KEY_8), SHIFT(KEY_9), SHIFT(KEY_0),
//  KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_0, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
//  SHIFT(KEY_TILDE), 0, 0, KEY_LEFT_BRACE, SHIFT(KEY_LEFT_BRACE), KEYBOARD_LEFT_ALT, SHIFT(KEY_RIGHT_BRACE), KEY_RIGHT_BRACE, KEY_BACKSLASH, KEY_BACKSPACE, KEY_EQUAL,
//  FUNCTION(2), SHIFT(KEY_INSERT), KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_DELETE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), 0, 0, 0 };

int layer1[44] = {
  SHIFT(KEY_8), KEY_9, KEY_8, KEY_7, SHIFT(KEY_3), KEY_0,SHIFT(KEY_RIGHT_BRACE), SHIFT(KEY_LEFT_BRACE), KEY_UP, SHIFT(KEY_2), SHIFT(KEY_1),
  SHIFT(KEY_EQUAL), KEY_6, KEY_5, KEY_4,SHIFT(KEY_6), KEY_0, SHIFT(KEY_5), KEY_RIGHT, KEY_DOWN, KEY_LEFT, SHIFT(KEY_4),
  0, KEY_3, KEY_2, KEY_1, SHIFT(KEY_BACKSLASH),KEYBOARD_LEFT_ALT, SHIFT(KEY_7), SHIFT(KEY_0), SHIFT(KEY_9), KEY_RIGHT_BRACE, KEY_LEFT_BRACE,
  KEY_EQUAL, KEY_0, KEY_BACKSLASH, 0, 0, 0, 0, FUNCTION(0), SHIFT(KEY_8), KEY_INSERT, 0 };

// int layer2[44] = {
//  KEY_HOME, KEY_UP, KEY_END, KEY_INSERT, KEY_PAGE_UP, KEY_0, KEY_UP, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
//  KEY_LEFT, KEY_DOWN, KEY_RIGHT, KEY_DELETE, KEY_PAGE_DOWN, KEY_0, KEY_DOWN, KEY_F4, KEY_F5, KEY_F6, KEY_F11,
//  0, 0, 0, 0, 0, KEYBOARD_LEFT_ALT, 0, KEY_F1, KEY_F2, KEY_F3, KEY_F12,
//  0, 0, KEYBOARD_LEFT_GUI, KEYBOARD_LEFT_SHIFT, KEY_BACKSPACE, KEYBOARD_LEFT_CTRL, KEY_SPACE, PRE_FUNCTION(1), 0, 0, FUNCTION(0) };

//int layer2[44] = {
//  KEY_F10, KEY_F9, KEY_F8, KEY_F7, KEY_UP, KEY_0, KEY_PAGE_UP, KEY_END, KEY_UP, KEY_HOME, KEY_INSERT,
//  KEY_F11, KEY_F6, KEY_F5, KEY_F4, KEY_DOWN, KEY_0, KEY_PAGE_DOWN, KEY_RIGHT, KEY_DOWN, KEY_LEFT, KEY_DELETE,
//  0, KEY_F3, KEY_F2, KEY_F1, 0, 0, 0, 0, 0, 0, 0,
//  KEY_F12, 0, SHIFT(KEY_BACKSLASH), FUNCTION(0), 0, 0, 0, 0, 0, 0, 0 };

// int *layers[] = {layer0, layer1, layer2};
int *layers[] = {layer0, layer1};

#include "layout_common.h"








